// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZFDMoKPlKqLq1PubiXfH2oDU3_t4JF1g',
    appId: '1:1042950304627:web:0974f29000a0c1b3f44b06',
    messagingSenderId: '1042950304627',
    projectId: 'belajar-800f9',
    authDomain: 'belajar-800f9.firebaseapp.com',
    databaseURL: 'https://belajar-800f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-800f9.firebasestorage.app',
    measurementId: 'G-7MSW9H4815',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsnOrhwrSroVbdTicGB8ReetrebxepTuc',
    appId: '1:1042950304627:android:002f9617696e0f7af44b06',
    messagingSenderId: '1042950304627',
    projectId: 'belajar-800f9',
    databaseURL: 'https://belajar-800f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-800f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1g5X7m1KvR0_41ysj7v-6RAMUs7xiLkY',
    appId: '1:1042950304627:ios:4147a8e537652b9bf44b06',
    messagingSenderId: '1042950304627',
    projectId: 'belajar-800f9',
    databaseURL: 'https://belajar-800f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-800f9.firebasestorage.app',
    iosBundleId: 'com.example.structur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1g5X7m1KvR0_41ysj7v-6RAMUs7xiLkY',
    appId: '1:1042950304627:ios:4147a8e537652b9bf44b06',
    messagingSenderId: '1042950304627',
    projectId: 'belajar-800f9',
    databaseURL: 'https://belajar-800f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-800f9.firebasestorage.app',
    iosBundleId: 'com.example.structur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZFDMoKPlKqLq1PubiXfH2oDU3_t4JF1g',
    appId: '1:1042950304627:web:34cf4ca7ab6028c5f44b06',
    messagingSenderId: '1042950304627',
    projectId: 'belajar-800f9',
    authDomain: 'belajar-800f9.firebaseapp.com',
    databaseURL: 'https://belajar-800f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-800f9.firebasestorage.app',
    measurementId: 'G-G56HLMQZDP',
  );
}
